version: "3"
services: 
  srtServer:
    image: "node:current-alpine"
    ports: 
      - '1234:1234'
    stdin_open: true
    tty: true
    volumes: 
      - "./:/var/fastSrtSubtitle"
      - "./start.sh:/usr/local/bin/start.sh"
    command: sh /usr/local/bin/start.sh
